### ISSUE TITLE
retrieve_instance_metadata() list/dict issue

### ISSUE THREAD

**Issue by lubanovic-flywheel** [clindatsci/dicomweb-client#14]
In `api,py`, the last line of `retrieve_instance_metadata()` is:
`return self._http_get_application_json(url)[0]`.
Shouldn't it be:
`return self._http_get_application_json(url)`?

**Comment by hackermd** [comment]
Metadata resources for study, series and instances represent a sequence of DICOM objects/instances (JSON array of mappings). In case of RetrieveInstanceMetadata, the sequence per definition contains only a single item, i.e. one DICOM object/instance. We decided to return the item rather than the sequence.
Does that answer your question?

**Comment by hackermd** [comment]
The payload of query or retrieve metadata response messages consists only of one JSON string, see DICOM PS3.18.
